version: '3.9'
services:
  tomcat:
    image: tomcat:latest
    ports:
      - "8080:8080"
    volumes:
      - ./target/t1_homework1-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/t1_homework1-1.0-SNAPSHOT.war
    restart:
      on-failure